sitemap-dev-php74-up:
	sudo UID=${UID} GID=${UID} docker-compose -f sitemap-dev-php7.4/docker-compose.yml up -d
sitemap-dev-php74-stop:
	sudo docker-compose -f sitemap-dev-php7.4/docker-compose.yml stop